import pandas as pd
import os

df = pd.read_csv(r'C:\Neuralretail\data\raw\online_retail_II.csv', encoding='latin-1')

missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)
missing_df = pd.DataFrame({'Missing Count': missing, 'Missing %': missing_pct})

duplicates = df.duplicated().sum()
cancelled = df['Invoice'].astype(str).str.startswith('C').sum()
negative_qty = (df['Quantity'] < 0).sum()
negative_price = (df['Price'] < 0).sum()
zero_price = (df['Price'] == 0).sum()
total_issues = missing['Customer ID'] + duplicates + cancelled + negative_qty + negative_price
quality_score = round((1 - total_issues/len(df)) * 100, 2)

html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Data Quality Report - NeuralRetail</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }}
        h1 {{ color: #E84E1B; }}
        h2 {{ color: #333; border-bottom: 2px solid #E84E1B; padding-bottom: 5px; }}
        table {{ border-collapse: collapse; width: 100%; background: white; }}
        th {{ background: #E84E1B; color: white; padding: 10px; text-align: left; }}
        td {{ padding: 10px; border-bottom: 1px solid #ddd; }}
        tr:hover {{ background: #f9f9f9; }}
        .score {{ font-size: 48px; font-weight: bold; color: #E84E1B; }}
        .card {{ background: white; padding: 20px; margin: 20px 0; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .good {{ color: green; font-weight: bold; }}
        .bad {{ color: red; font-weight: bold; }}
    </style>
</head>
<body>
    <h1>🛒 NeuralRetail - Data Quality Report</h1>
    <p>Dataset: UCI Online Retail II | Generated by: Amdox Task 3</p>

    <div class="card">
        <h2>📊 Overall Quality Score</h2>
        <div class="score">{quality_score}%</div>
        <p>After cleaning: <span class="good">98%+</span> valid rows</p>
    </div>

    <div class="card">
        <h2>📋 Basic Information</h2>
        <table>
            <tr><th>Metric</th><th>Value</th></tr>
            <tr><td>Total Rows</td><td>{df.shape[0]:,}</td></tr>
            <tr><td>Total Columns</td><td>{df.shape[1]}</td></tr>
            <tr><td>Columns</td><td>{', '.join(df.columns.tolist())}</td></tr>
        </table>
    </div>

    <div class="card">
        <h2>❓ Missing Values</h2>
        <table>
            <tr><th>Column</th><th>Missing Count</th><th>Missing %</th><th>Action</th></tr>
            <tr><td>Customer ID</td><td class="bad">{missing['Customer ID']:,}</td><td class="bad">22.77%</td><td>Removed — cannot identify customer</td></tr>
            <tr><td>Description</td><td>{missing['Description']:,}</td><td>0.41%</td><td>Kept — not needed for models</td></tr>
            <tr><td>All Others</td><td class="good">0</td><td class="good">0%</td><td>No action needed</td></tr>
        </table>
    </div>

    <div class="card">
        <h2>🔍 Duplicate Analysis</h2>
        <table>
            <tr><th>Metric</th><th>Value</th><th>Status</th></tr>
            <tr><td>Duplicate Rows</td><td>{duplicates:,}</td><td class="bad">Removed</td></tr>
            <tr><td>Duplicate %</td><td>3.22%</td><td class="bad">Removed</td></tr>
        </table>
    </div>

    <div class="card">
        <h2>✅ Validation Rules</h2>
        <table>
            <tr><th>Rule</th><th>Count</th><th>Action</th></tr>
            <tr><td>Cancelled Orders (Invoice starts with C)</td><td class="bad">{cancelled:,}</td><td>Removed</td></tr>
            <tr><td>Negative Quantities</td><td class="bad">{negative_qty:,}</td><td>Removed</td></tr>
            <tr><td>Negative Prices</td><td class="bad">{negative_price:,}</td><td>Removed</td></tr>
            <tr><td>Zero Prices</td><td class="bad">{zero_price:,}</td><td>Removed</td></tr>
        </table>
    </div>

    <div class="card">
        <h2>📈 After Cleaning</h2>
        <table>
            <tr><th>Metric</th><th>Before</th><th>After</th></tr>
            <tr><td>Total Rows</td><td>{df.shape[0]:,}</td><td class="good">805,549</td></tr>
            <tr><td>Valid Customer IDs</td><td class="bad">77.23%</td><td class="good">100%</td></tr>
            <tr><td>Valid Quantities</td><td class="bad">97.85%</td><td class="good">100%</td></tr>
            <tr><td>Valid Prices</td><td class="bad">99.41%</td><td class="good">100%</td></tr>
        </table>
    </div>

    <div class="card">
        <h2>🎯 Conclusion</h2>
        <p>The raw dataset had <strong>261,822 invalid rows</strong> removed during cleaning.</p>
        <p>The cleaned dataset of <strong>805,549 rows</strong> has <span class="good">98%+ data quality</span> and is ready for ML model training.</p>
    </div>
</body>
</html>
"""

os.makedirs('reports', exist_ok=True)
with open('reports/data_quality.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("HTML report saved to reports/data_quality.html")
